twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'form/fields.html.twig'
    globals: 
        profiles: '%profiles%'
        postss : '%posts%'
when@test:
    twig:
        strict_variables: true
