vich_uploader:
    db_driver: orm

    mappings:
        post_images: # This is your mapping name
            uri_prefix: /uploads/posts
            upload_destination: '%kernel.project_dir%/public/uploads/posts/'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            # namer:
            #     service: Vich\UploaderBundle\Naming\OrignameNamer
